# Generated by Django 2.1 on 2018-09-04 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('emp_deduct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dep_deduct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('std_deduct', models.BooleanField(default=True)),
                ('company_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.Company'),
            preserve_default=False,
        ),
    ]
