# Generated by Django 2.1 on 2018-09-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20180904_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dependents',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
