# Generated by Django 2.1.1 on 2018-09-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_dependent_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dependents',
            field=models.IntegerField(default=0),
        ),
    ]
