# Generated by Django 2.1.1 on 2018-09-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20180913_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dependents',
        ),
        migrations.AddField(
            model_name='company',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='company',
            name='discount_policy',
            field=models.CharField(default='a', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependent',
            name='deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
