# Generated by Django 2.1.1 on 2018-09-14 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20180913_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependent',
            name='deduction',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='deduction',
        ),
    ]
