# Generated by Django 2.1.1 on 2018-09-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20180914_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='percent_co_pays',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='employee',
            name='percent_co_pays',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
