# Generated by Django 2.1.1 on 2018-09-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20180914_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependent',
            name='percent_co_pays',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='percent_co_pays',
        ),
        migrations.AddField(
            model_name='company',
            name='contribution_percent',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=7),
            preserve_default=False,
        ),
    ]
