# Generated by Django 2.1.1 on 2018-09-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20180914_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='std_deduct',
        ),
    ]
